# -*- coding: utf-8 -*-
import csv,re



aaa = {
    "Message": "",
    "ResponseCode": "00",
    "MaxRangeDate": "/Date(1569833793423-0500)/",
    "StationList": [
        {
            "CountryCode": "MX ",
            "Destinations": [
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/ACA/ACABIG.png",
            "International": "0",
            "Latitude": 16.7615213,
            "Longitude": -99.7611067,
            "Name": "Gral. Juan N. Alvarez Int. Airport",
            "ShortName": "Acapulco",
            "StationCode": "ACA",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "SAT",
                "SFB",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/AGU/AGUBIG.png",
            "International": "0",
            "Latitude": 21.6972854,
            "Longitude": -102.3158632,
            "Name": "Lic. Jesus Teran Peredo Int. Airport",
            "ShortName": "Aguascalientes",
            "StationCode": "AGU",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CO ",
            "Destinations": [
                "ACA",
                "AGU",
                "BGA",
                "BJX",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/BOG/BOGBIG.png",
            "International": "1",
            "Latitude": 4.6989653,
            "Longitude": -74.1415816,
            "Name": "El Dorado Int. Airport",
            "ShortName": "Bogota",
            "StationCode": "BOG",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CPE/CPEBIG.png",
            "International": "0",
            "Latitude": 19.814763,
            "Longitude": -90.5009505,
            "Name": "Ing. Alberto Acuña Ongay Int. Airport",
            "ShortName": "Campeche",
            "StationCode": "CPE",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "ADZ",
                "AGU",
                "ANF",
                "ARI",
                "BAQ",
                "BBA",
                "BGA",
                "BJX",
                "BOG",
                "CCP",
                "CEN",
                "CJC",
                "CJS",
                "CLE",
                "CLO",
                "CME",
                "CMH",
                "CPE",
                "CPO",
                "CTG",
                "CTM",
                "CUC",
                "CUL",
                "CUU",
                "CZM",
                "DFW",
                "EYP",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LET",
                "LIM",
                "LSC",
                "MCO",
                "MDE",
                "MEX",
                "MHC",
                "MIA",
                "MTR",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PEI",
                "PIT",
                "PMC",
                "PQM",
                "PUQ",
                "PVR",
                "PXM",
                "RDU",
                "REX",
                "SAT",
                "SCL",
                "SFB",
                "SFO",
                "SJD",
                "SJO",
                "SLP",
                "SMR",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "VUP",
                "WCA",
                "YUL",
                "YVR",
                "YYZ",
                "ZAL",
                "ZCO",
                "ZIH",
                "ZOS"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CUN/CUNBIG.png",
            "International": "0",
            "Latitude": 21.0403409,
            "Longitude": -86.873564,
            "Name": "Cancun Int. Airport",
            "ShortName": "Cancun",
            "StationCode": "CUN",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "JFK",
                "LAP",
                "LAS",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "SAT",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CTM/CTMBIG.png",
            "International": "0",
            "Latitude": 18.5063952,
            "Longitude": -88.3242963,
            "Name": "Chetumal Int. Airport",
            "ShortName": "Chetumal",
            "StationCode": "CTM",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "LAP",
                "LIM",
                "MEX",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "PVR",
                "PXM",
                "SAT",
                "SJD",
                "SJO",
                "TAM",
                "TGZ",
                "TIJ",
                "VER",
                "VSA",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/ORD/ORDBIG.png",
            "International": "1",
            "Latitude": 41.9741625,
            "Longitude": -87.9073214,
            "Name": "O’Hare Int. Airport",
            "ShortName": "Chicago",
            "StationCode": "ORD",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CUU/CUUBIG.png",
            "International": "0",
            "Latitude": 28.7024502,
            "Longitude": -105.9626205,
            "Name": "Gral. Roberto Fierro Villalobos Int. Airport",
            "ShortName": "Chihuahua",
            "StationCode": "CUU",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH",
                "ZLO"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CME/CMEBIG.png",
            "International": "0",
            "Latitude": 18.6510343,
            "Longitude": -91.8024457,
            "Name": "Ciudad del Carmen Int. Airport",
            "ShortName": "Ciudad del Carmen",
            "StationCode": "CME",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CJS/CJSBIG.png",
            "International": "0",
            "Latitude": 31.6362604,
            "Longitude": -106.4362549,
            "Name": "Abraham Gonzalez Int. Airport",
            "ShortName": "Ciudad Juarez",
            "StationCode": "CJS",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "DFW",
                "GDL",
                "HAV",
                "HMO",
                "HUX",
                "JFK",
                "LAX",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "OAX",
                "ORD",
                "REX",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CEN/CENBIG.png",
            "International": "0",
            "Latitude": 27.3979855,
            "Longitude": -109.8342837,
            "Name": "Ciudad Obregon Int. Airport",
            "ShortName": "Ciudad Obregon",
            "StationCode": "CEN",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "REX",
                "SAT",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CZM/CZMBIG.png",
            "International": "0",
            "Latitude": 20.5228758,
            "Longitude": -86.9258953,
            "Name": "Cozumel Int. Airport",
            "ShortName": "Cozumel",
            "StationCode": "CZM",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/CUL/CULBIG.png",
            "International": "0",
            "Latitude": 24.7666548,
            "Longitude": -107.4701623,
            "Name": "Bachigualato Int. Airport",
            "ShortName": "Culiacan",
            "StationCode": "CUL",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "LIM",
                "MEX",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SJD",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "VER",
                "VSA",
                "ZIH",
                "ZLO"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/DFW/DFWBIG.png",
            "International": "1",
            "Latitude": 32.8946537,
            "Longitude": -97.0622324,
            "Name": "Dallas-Fort Worth Int. Airport",
            "ShortName": "Dallas",
            "StationCode": "DFW",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SFB",
                "SFO",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/GDL/GDLBIG.png",
            "International": "0",
            "Latitude": 20.5259561,
            "Longitude": -103.307625,
            "Name": "Miguel Hidalgo y Costilla Int. Airport",
            "ShortName": "Guadalajara",
            "StationCode": "GDL",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "GT ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SFB",
                "SJD",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/GUA/GUABIG.png",
            "International": "1",
            "Latitude": 14.583263,
            "Longitude": -90.527463,
            "Name": "La Aurora Int. Airport",
            "ShortName": "Guatemala",
            "StationCode": "GUA",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SFO",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/HMO/HMOBIG.png",
            "International": "0",
            "Latitude": 29.090096,
            "Longitude": -111.0517955,
            "Name": "Gral. Ignacio Pesqueira Garcia Int. Airport",
            "ShortName": "Hermosillo",
            "StationCode": "HMO",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HUX",
                "JFK",
                "LAP",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/IAH/IAHBIG.png",
            "International": "1",
            "Latitude": 29.5311973,
            "Longitude": -98.4683484,
            "Name": "George Bush Int. Airport",
            "ShortName": "Houston",
            "StationCode": "IAH",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/HUX/HUXBIG.png",
            "International": "0",
            "Latitude": 15.7730474,
            "Longitude": -96.259423,
            "Name": "Bahias de Huatulco Int. Airport",
            "ShortName": "Huatulco",
            "StationCode": "HUX",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CU ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "REX",
                "SAT",
                "SFO",
                "SJO",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/HAV/HAVBIG.png",
            "International": "1",
            "Latitude": 22.9891669,
            "Longitude": -82.409167,
            "Name": "Jose Marti Int. Airport",
            "ShortName": "La Habana",
            "StationCode": "HAV",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "GDL",
                "HMO",
                "HUX",
                "IAH",
                "LIM",
                "MEX",
                "MID",
                "MTT",
                "MTY",
                "OAX",
                "ORD",
                "REX",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VSA"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/LAP/LAPBIG.png",
            "International": "0",
            "Latitude": 24.0753587,
            "Longitude": -110.3644232,
            "Name": "Manuel Marquez de León Int. Airport",
            "ShortName": "La Paz",
            "StationCode": "LAP",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "BJX",
                "CTM",
                "CUN",
                "GDL",
                "LIM",
                "MEX",
                "MTY",
                "SNU",
                "TGZ",
                "TRC",
                "VSA",
                "YUL",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/LAS/LASBIG.png",
            "International": "1",
            "Latitude": 36.0839998,
            "Longitude": -115.1537389,
            "Name": "McCarran Int. Airport",
            "ShortName": "Las Vegas",
            "StationCode": "LAS",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "SAT",
                "SFB",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH",
                "ZLO"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/BJX/BJXBIG.png",
            "International": "0",
            "Latitude": 20.993517,
            "Longitude": -101.4805699,
            "Name": "Bajío Int. Airport",
            "ShortName": "Leon/Bajio",
            "StationCode": "BJX",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "PE ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "CJS",
                "CME",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PVR",
                "SAT",
                "SFB",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/LIM/LIMBIG.png",
            "International": "1",
            "Latitude": -12.0252229,
            "Longitude": -77.1118129,
            "Name": "Jorge Chavez Int. Airport",
            "ShortName": "Lima",
            "StationCode": "LIM",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CPE",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "LIM",
                "MEX",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "PVR",
                "PXM",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/LAX/LAXBIG.png",
            "International": "1",
            "Latitude": 33.9415889,
            "Longitude": -118.40853,
            "Name": "Los Angeles Int. Airport",
            "ShortName": "Los Angeles",
            "StationCode": "LAX",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SJD/SJDBIG.png",
            "International": "0",
            "Latitude": 23.1455358,
            "Longitude": -109.7182665,
            "Name": "Los Cabos Int. Airport",
            "ShortName": "Los Cabos",
            "StationCode": "SJD",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "OAX",
                "ORD",
                "PVR",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/MZT/MZTBIG.png",
            "International": "0",
            "Latitude": 23.1647221,
            "Longitude": -106.2677603,
            "Name": "Gral. Rafael Buelna Int. Airport",
            "ShortName": "Mazatlan",
            "StationCode": "MZT",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SFB",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/MID/MIDBIG.png",
            "International": "0",
            "Latitude": 20.9335196,
            "Longitude": -89.6629643,
            "Name": "Manuel Crescencio Rejon Int. Airport",
            "ShortName": "Merida",
            "StationCode": "MID",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "ADZ",
                "AGU",
                "ANF",
                "ARI",
                "BAQ",
                "BBA",
                "BGA",
                "BJX",
                "BOG",
                "CCP",
                "CEN",
                "CJC",
                "CJS",
                "CLO",
                "CME",
                "CPE",
                "CPO",
                "CTG",
                "CTM",
                "CUC",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "EYP",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "IPC",
                "IQQ",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LET",
                "LIM",
                "LSC",
                "LTO",
                "MCO",
                "MDE",
                "MFE",
                "MHC",
                "MIA",
                "MID",
                "MSP",
                "MTR",
                "MTT",
                "MTY",
                "MZT",
                "NAS",
                "OAX",
                "ORD",
                "PEI",
                "PHX",
                "PMC",
                "PQM",
                "PUQ",
                "PVR",
                "PXM",
                "SAT",
                "SCL",
                "SFB",
                "SFO",
                "SJD",
                "SJO",
                "SLP",
                "SMR",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "VUP",
                "WCA",
                "YUL",
                "YVR",
                "YYZ",
                "ZAL",
                "ZCO",
                "ZIH",
                "ZOS"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/MEX/MEXBIG.png",
            "International": "0",
            "Latitude": 19.4345862,
            "Longitude": -99.0847155,
            "Name": "Benito Juarez Int. Airport",
            "ShortName": "Mexico City",
            "StationCode": "MEX",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LIM",
                "MEX",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/MIA/MIABIG.png",
            "International": "1",
            "Latitude": 25.795865,
            "Longitude": -80.2870457,
            "Name": "Miami Int. Airport",
            "ShortName": "Miami",
            "StationCode": "MIA",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "JFK",
                "LAP",
                "LAX",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SAT",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/MTT/MTTBIG.png",
            "International": "0",
            "Latitude": 18.1024782,
            "Longitude": -94.5779807,
            "Name": "Minatitlan Int. Airport",
            "ShortName": "Minatitlan",
            "StationCode": "MTT",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BGA",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "QRO",
                "REX",
                "SAT",
                "SFB",
                "SFO",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/MTY/MTYBIG.png",
            "International": "0",
            "Latitude": 25.7778185,
            "Longitude": -100.1079853,
            "Name": "Gral. Mariano Escobedo Int. Airport",
            "ShortName": "Monterrey",
            "StationCode": "MTY",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CA ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "LAS",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SFO",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/YUL/YULBIG.png",
            "International": "1",
            "Latitude": 19.123,
            "Longitude": 19.123,
            "Name": "Pierre Elliott Trudeau",
            "ShortName": "Montreal",
            "StationCode": "YUL",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://content.interjet.com/media/1591/vuelos-nueva-york_header_es-mx.jpg",
            "International": "1",
            "Latitude": 40.6413111,
            "Longitude": -73.7781391,
            "Name": "John F. Kennedy Int. Airport",
            "ShortName": "New York",
            "StationCode": "JFK",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/OAX/OAXBIG.png",
            "International": "0",
            "Latitude": 17.0004016,
            "Longitude": -96.7245653,
            "Name": "Xoxocotlan Int. Airport",
            "ShortName": "Oaxaca",
            "StationCode": "OAX",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "AGU",
                "BJX",
                "CUN",
                "GDL",
                "GUA",
                "LIM",
                "MEX",
                "MID",
                "MTY",
                "SNU",
                "TGZ",
                "TRC",
                "VSA",
                "YVR"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SFB/SFBBIG.png",
            "International": "1",
            "Latitude": 28.429444,
            "Longitude": -81.308889,
            "Name": "Orlando International Airport",
            "ShortName": "Orlando",
            "StationCode": "MCO",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "AGU",
                "BJX",
                "CUN",
                "GDL",
                "GUA",
                "LIM",
                "MEX",
                "MID",
                "MTY"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SFB/SFBBIG.png",
            "International": "1",
            "Latitude": 28.7754835,
            "Longitude": -81.2454415,
            "Name": "Sanford Int. Airport",
            "ShortName": "Orlando Sanford",
            "StationCode": "SFB",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "OAX",
                "REX",
                "SAT",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/PQM/PQMBIG.png",
            "International": "0",
            "Latitude": 17.5334022,
            "Longitude": -92.0170518,
            "Name": "Palenque Int. Airport",
            "ShortName": "Palenque",
            "StationCode": "PQM",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "OAX",
                "ORD",
                "PVR",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/PXM/PXMBIG.png",
            "International": "0",
            "Latitude": 15.8759957,
            "Longitude": -97.0929607,
            "Name": "Puerto Escondido Int. Airport",
            "ShortName": "Puerto Escondido",
            "StationCode": "PXM",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAN",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PXM",
                "QRO",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/PVR/PVRBIG.png",
            "International": "0",
            "Latitude": 20.6805184,
            "Longitude": -105.2523762,
            "Name": "Lic. Gustavo Diaz Ordaz Int. Airport",
            "ShortName": "Puerto Vallarta",
            "StationCode": "PVR",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "JFK",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SAT/SATBIG.png",
            "International": "1",
            "Latitude": 29.5311973,
            "Longitude": -98.4683484,
            "Name": "San Antonio Int. Airport",
            "ShortName": "San Antonio",
            "StationCode": "SAT",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "US ",
            "Destinations": [
                "CUN",
                "GDL",
                "HAV",
                "HMO",
                "MEX",
                "MTY",
                "YUL"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SFO/SFOBIG.png",
            "International": "1",
            "Latitude": 37.6194444444,
            "Longitude": -122.3727777778,
            "Name": "San Francisco International Airport",
            "ShortName": "San Francisco",
            "StationCode": "SFO",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CR ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SJO/SJOBIG.png",
            "International": "1",
            "Latitude": 9.9581347,
            "Longitude": -84.1395561,
            "Name": "Juan Santamaria Int. Airport",
            "ShortName": "San Jose",
            "StationCode": "SJO",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "JFK",
                "LAP",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SLP/SLPBIG.png",
            "International": "0",
            "Latitude": 22.2568861,
            "Longitude": -100.9341508,
            "Name": "Ponciano Arriaga Int. Airport",
            "ShortName": "San Luis Potosi",
            "StationCode": "SLP",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CU ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/SNU/SNUBIG.png",
            "International": "1",
            "Latitude": 22.49194,
            "Longitude": -79.94361,
            "Name": "Abel Santamaria Int. Airport",
            "ShortName": "Santa Clara",
            "StationCode": "SNU",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/TAM/TAMBIG.png",
            "International": "0",
            "Latitude": 22.2910421,
            "Longitude": -97.8663616,
            "Name": "Gral. Francisco Javier Mina Int. Airport",
            "ShortName": "Tampico",
            "StationCode": "TAM",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/TIJ/TIJBIG.png",
            "International": "0",
            "Latitude": 32.5422546,
            "Longitude": -116.9717004,
            "Name": "Tijuana-San Diego Binational Airport",
            "ShortName": "Tijuana",
            "StationCode": "TIJ",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "CME",
                "CUN",
                "CUU",
                "GDL",
                "HAV",
                "IAH",
                "LAP",
                "MEX",
                "MTY",
                "PVR",
                "SJD",
                "TIJ",
                "VER",
                "VSA",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/TLC/TLCBIG.png",
            "International": "0",
            "Latitude": 19.3388764,
            "Longitude": -99.5721869,
            "Name": "Lic. Adolfo Lopez Mateos Int. Airport",
            "ShortName": "Toluca",
            "StationCode": "TLC",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CA ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "LAS",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MUD",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/YYZ/YYZBIG.png",
            "International": "1",
            "Latitude": 43.677718,
            "Longitude": -79.62482,
            "Name": "Toronto Pearson Int. Airport",
            "ShortName": "Toronto",
            "StationCode": "YYZ",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "QRO",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/TRC/TRCBIG.png",
            "International": "0",
            "Latitude": 25.5657323,
            "Longitude": -103.4049644,
            "Name": "Francisco Sarabia Int. Airport",
            "ShortName": "Torreon",
            "StationCode": "TRC",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TIJ",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/TGZ/TGZBIG.png",
            "International": "0",
            "Latitude": 16.5606549,
            "Longitude": -93.0192422,
            "Name": "Angel Albino Corzo Int. Airport",
            "ShortName": "Tuxtla Gutierrez",
            "StationCode": "TGZ",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CA ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTY",
                "MZT",
                "OAX",
                "PQM",
                "PVR",
                "PXM",
                "SJD",
                "SJO",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/YVR/YVRBIG.png",
            "International": "1",
            "Latitude": 49.246292,
            "Longitude": -123.116226,
            "Name": "Vancouver International Airport  ",
            "ShortName": "Vancouver",
            "StationCode": "YVR",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "CU ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "CUN",
                "GDL",
                "GUA",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "OAX",
                "REX",
                "SJO",
                "SLP",
                "TAM",
                "TGZ",
                "TIJ",
                "TRC",
                "VER",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/VRA/VRABIG.png",
            "International": "1",
            "Latitude": 23.1235064,
            "Longitude": -81.3034921,
            "Name": "Juan Gualberto Gomez Airport",
            "ShortName": "Varadero",
            "StationCode": "VRA",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/VER/VERBIG.png",
            "International": "0",
            "Latitude": 19.1448114,
            "Longitude": -96.1863998,
            "Name": "Gral. Heriberto Jara Int. Airport",
            "ShortName": "Veracruz",
            "StationCode": "VER",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "ACA",
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "CZM",
                "DFW",
                "GDL",
                "GUA",
                "HAV",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAP",
                "LAS",
                "LAX",
                "LIM",
                "MCO",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PQM",
                "PVR",
                "PXM",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "YUL",
                "YVR",
                "YYZ",
                "ZIH"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/VSA/VSABIG.png",
            "International": "0",
            "Latitude": 17.9955545,
            "Longitude": -92.8189979,
            "Name": "Carlos Rovirosa Perez Int. Airport",
            "ShortName": "Villahermosa",
            "StationCode": "VSA",
            "StationGroup": "ALL"
        },
        {
            "CountryCode": "MX ",
            "Destinations": [
                "AGU",
                "BJX",
                "BOG",
                "CEN",
                "CJS",
                "CME",
                "CPE",
                "CTM",
                "CUL",
                "CUN",
                "CUU",
                "DFW",
                "GDL",
                "GUA",
                "HMO",
                "HUX",
                "IAH",
                "JFK",
                "LAX",
                "LIM",
                "MEX",
                "MIA",
                "MID",
                "MTT",
                "MTY",
                "MZT",
                "OAX",
                "ORD",
                "PVR",
                "REX",
                "SAT",
                "SJD",
                "SJO",
                "SLP",
                "SNU",
                "TAM",
                "TGZ",
                "TIJ",
                "TLC",
                "TRC",
                "VER",
                "VRA",
                "VSA",
                "YUL",
                "YVR",
                "YYZ"
            ],
            "Distance": 0,
            "DistanceUnit": "mi",
            "ImageURL": "https://static.interjet.com/assets/images/destinies/SEO/ZIH/ZIHBIG.png",
            "International": "0",
            "Latitude": 17.6061647,
            "Longitude": -101.4633309,
            "Name": "Ixtapa-Zihuatanejo Int. Airport",
            "ShortName": "Zihuatanejo",
            "StationCode": "ZIH",
            "StationGroup": "ALL"
        }
    ]
}



list= aaa.get('StationList')
vvv = []
OutputFile = open('4O.csv', 'wb')
writer = csv.writer(OutputFile)
for bb in list:
    dep = bb.get('StationCode')
    for to in bb.get('Destinations'):
        if dep == to:
            continue
        vvv.append([dep,to])
vvv.sort()
for ss in vvv:

    writer.writerow([ss[0], ss[1]])
    print(ss[0], ss[1])

OutputFile.close()

